Repository ryanfaiz/quakewatch, pull requests merged in 2024-11, with the labels that each got.

#4 QuakeWatch v1.1.1
  docs/PULL_REQUEST_TEMPLATE.md
  main.py
  options.txt
Labels: enhancement

#5 QuakeWatch v1.1.2
  main.py
Labels: enhancement

#6 QuakeWatch v1.2.0
  main.py
Labels: documentation

#7 QuakeWatch v1.2.1
  data-gempa.csv
  main.py
  options.txt
Labels: bug

#8 QuakeWatch v1.2.2
  data-gempa.csv
  main.py
  options.txt
Labels: bug

#9 v1.2.4
  main.py
Labels: bug
